### Criteo dataset convert to movielens dataset
movielens_x4:
    data_root: ./data/movielens/
    data_format: csv
    train_data: ./data/movielens_x/train.csv
    valid_data: ./data/movielens_x/valid.csv
    test_data: ./data/movielens_x/test.csv
    min_categr_count: 10
    data_block_size: -1
    feature_cols:
        - {name: ["userid","gender","age","occupation","movieid","year"],
           active: True, dtype: float, type: categorical, na_value: 0}
        - {name: ["Action","Adventure","Animation","Children's","Comedy","Crime","Documentary","Drama","Fantasy",
            "Film-Noir","Horror","Musical","Mystery","Romance","Sci-Fi","Thriller","War","Western"],
           active: True, dtype: float, type: categorical, na_value: 0}
    label_col: {name: label, dtype: float}

    