movielens_x4_d7d029e8:
    data_format: csv
    data_root: ../data/movielens
    feature_cols:
    -   active: true
        dtype: float
        na_value: 0
        name: [userid, gender, age, occupation, movieid, year]
        type: categorical
    -   active: true
        dtype: float
        na_value: 0
        name: [Action, Adventure, Animation, Children's, Comedy, Crime, Documentary,
            Drama, Fantasy, Film-Noir, Horror, Musical, Mystery, Romance, Sci-Fi,
            Thriller, War, Western]
        type: categorical
    label_col: {dtype: float, name: label}
    test_data: ../data/movielens_x4/test.csv
    train_data: ../data/movielens_x4/train.csv
    valid_data: ../data/movielens_x4/valid.csv
