base_config: ../config/gafm4_avazu_x4/
base_expid: gafm4_avazu_x4
dataset_id: avazu_x4
dataset_config:
    criteo_x4:
        data_format: csv
        data_root: '../data/avazu'
        train_data: ../data/avazu_x4/train.csv
        valid_data: ../data/avazu_x4/valid.csv
        test_data: ../data/avazu_x4/test.csv
        feature_cols:
        - {name: id, active: False, dtype: str, type: categorical}
        - {name: hour, active: True, dtype: str, type: categorical, preprocess: convert_hour}
        - {name: [C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,
                  device_ip,device_model,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21], 
           active: True, dtype: str, type: categorical}
        - {name: weekday, active: True, dtype: str, type: categorical, preprocess: convert_weekday}
        - {name: weekend, active: True, dtype: str, type: categorical, preprocess: convert_weekend}
        label_col: {name: click, dtype: float}

tuner_space:
    embedding_dim: [40, 16]
    learning_rate: [1.e-3, 1.e-4]
    # dnn_hidden_units: [[500,500,500,500,500],[1000,1000,1000,1000,1000]]
    # cin_layer_units: [[64, 64, 64], [64, 64]]
    # net_dropout: 0.2
    # embedding_regularizer: [1.e-4, 1.e-3]
    batch_size: [1000, 512]
    seed: 2019