Base: 
    model_root: './checkpoints/'
    workers: 8
    verbose: 1
    patience: 2
    pickle_feature_encoder: True
    use_hdf5: True
    save_best_only: True
    every_x_epochs: 1
    debug: False


fignn+fm_kkbox_x1:
    model: FiGNN_FM
    dataset_id: kkbox_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 1000
    embedding_dim: 40
    gnn_layers: 3
    use_residual: False  # True
    use_gru: False  #True
    reuse_graph_layer: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
